### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by Occhiii623** [Yuto-chan/freemarket_sample_74h#30]
■ URL
IPアドレス：54.168.43.9
Github（最終課題のリポジトリ）：https://github.com/Yuto-chan/freemarket_sample_74h

■ Basic認証
ID：Yuto-chan
Pass：ppf5p3dn

■ テスト用アカウント
◯ 購入者用
メールアドレス：mayumi@gmail.com
パスワード：mayumayu

◯ 購入用カード情報
番号：4242424242424242
期限：7/25
セキュリティカード：123

◯ 出品者用
メールアドレス：test@gmail.com
パスワード：testtest

**Comment by miyu-yamamoto** [comment]
提出ありがとうございます！
確認させて頂いたところ、ログイン後何かの動作を行うと
またすぐに認証画面が表示されてしまうため実装の確認が行えません。
最初のログイン時以外は表示されないように修正をお願いします。
<img width="1431" alt="スクリーンショット 2020-05-26 11 40 31" src="https://user-images.githubusercontent.com/59544869/82855271-d5fe6400-9f45-11ea-9028-f682299113f3.png">

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfMuna4xX0zQ6_L8vRFrevse1I8VkCcdMp-24egzeH_JmIllg/viewform

※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。

**Comment by Occhiii623** [comment]
> 提出ありがとうございます！
> 確認させて頂いたところ、ログイン後何かの動作を行うと
> またすぐに認証画面が表示されてしまうため実装の確認が行えません。
> 最初のログイン時以外は表示されないように修正をお願いします。

> 
> 修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
> https://docs.google.com/forms/d/e/1FAIpQLSfMuna4xX0zQ6_L8vRFrevse1I8VkCcdMp-24egzeH_JmIllg/viewform
> 

確認ありがとうございます！
ログインしていない状態だと、トップページに戻るたびに認証を求められるという件ですが
チームメンバーの環境ですと特に動作は問題なく、
原因となりうる箇所を確認したうえでメンターの方にも伺ったところ、コードは特に問題なく、Chhromeの仕様でこうなってしまってる可能性が高いそうです。

以下、メンターの方からの回答です。
ーーーーーーーー
①か②の方法を行うと「トップページ戻るたびにbasic認証を求められる」状態は解消できます
　　　↓↓↓
①Chromeではなくサファリからアプリを開く
②Chromeの「設定」→「自動入力」→「パスワード」に行き、ONになっている自動ログイン機能をOFFにする
https://gyazo.com/04cae68517a7288c67305bb40a637324
最終課題のコードレビュワーの方には上の方法でチェックしてもらうよう伝えてください
ーーーーーーーー

お手数をおかけしてしまい、申し訳ありませんが
何卒よろしくお願いいたします。

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
